name: Run Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.5
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Activate virtual environment and install module
      run: |
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run test
      run: |
        python -m pytest -vv tests/test_smoke.py
